### ISSUE TITLE
2 - mettre à jour un second film sur la page

### ISSUE THREAD

**Issue by yanngv29** [yanngv29/ensim-git-tp1#2]
mettre à jour un film sur la page pour qu'il corresponde à un film actuellement a l'affiche dans une salle du Mans.
Il faut changer l'image, le texte , les horaires, etc ...

**Comment by worldroot** [comment]
will work on it

**Comment by yanngv29** [comment]
J'ai été trop confiant ... tu n'a pas changé le nom du film dans la liste des "showtimes"  ( à la place de Ghost in the shell)
